### PR TITLE
[UI] Dashboard Layout & Sidebar

### LINKED ISSUE #1: [UI] Dashboard Layout
Minimal Dashboard Layout with following requirements:

- Sidebar from Shadcn
- Workspace selector at top of the sidebar
- Sidebar Items: Links, Analytics, Settings

..._WIP_

### PR DESCRIPTION
**Pull request by henilmalaviya**

### CODE REVIEW

**Comment by henilmalaviya** [comment]
Merging PR as of now. will see what to do about API Keys and Analytics Page.

**Comment by henilmalaviya** [comment]
@RajBhut congrats on first PR :partying_face:

**Comment by henilmalaviya** [comment]
pipeline building on `main`

**Comment by RajBhut** [comment]
> @RajBhut congrats on first PR :partying_face: 
🙌🥳

**Pull request merged**
